#!/usr/bin/env python3
#Gets the sheet names of an excel file

import xlrd
import sys

def getSheetName(file_name):
    names = []
    Workbook = xlrd.open_workbook(file_name, on_demand=True)
    names = Workbook.sheet_names()
    
    for name in names:
        print(name)



if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(" Usage: %s results.csv > entries.csv" % sys.argv[0])
        sys.exit(1)
    sys.exit(getSheetName(sys.argv[1]))