#!/usr/bin/env python3
# Given a results.csv as outputted by rpu-parse, parse each sheet one at a time
# and join all the sheets together into an OpenPowerlifting-formatted CSV file.

import sys

sys.path.append('../../scripts')
sys.path.append('scripts')
import oplcsv
import re

def die(s):
    print(s, file=sys.stderr)
    sys.exit(1)


# Given the array of lines, split it up into an array per-sheet.
def split_by_sheet(lines):
    # Skip past the overview.
    for i in range(len(lines)):
        if 'Sheet' in lines[i][0]:
            break
    assert i < len(lines)
    assert 'Sheet' in lines[i][0]

    sheetlist = []
    sheet = None

    for line in lines[i:]:
        # If this line starts a new sheet, generate a new array.
        if 'Sheet' in line[0]:
            sheet = []
            sheetlist.append(sheet)
        sheet.append(line)

    return sheetlist


# Given the name of a sheet, return a dictionary describing the sheet.
def parse_sheetname(s):
    obj = {}

    event = None
    amateur = 'Pro' # By default, unless otherwise specified.
    equipment = 'Multi-ply' # By default, unless otherwise specified.

    # Parse word-by-word to make sure that every word is understood. 
    s=s.lower()



    s= s.replace('.',' ').replace('"','').replace('_',' ').replace('(',' ').replace(')',' ')
    s = s.replace(' & ','&')
    s = s.replace('лист','') #Sheet
    for word in s.split():
 

        # Events
        if word in ['пл','пауэрлифтинг','pl','пауэрифтинг','пауэлифтинг','ча-пл','ка-пл','паурлифтинг','троеборье']:
            assert not event
            event = 'SBD'
        elif word == 'присед' or word == 'sq':
            assert not event
            event = 'S'
        elif word in ['жим','bp','bench','жд']:
            assert not event or event == 'B'
            event = 'B'
            if equipment == 'Wraps':
                equipment = 'Raw'
        elif word == 'тяга' or word == 'dl':
            assert not event
            event = 'D'
            if equipment == 'Wraps':
                equipment = 'Raw'
        elif word in ['двоеборье','pp','ж+т','bp+dl','push&pull','cил']:
            assert not event
            event = 'BD'
            if equipment == 'Wraps':
                equipment = 'Raw'

        # Equipment
        elif word in ['однослой','однослое','односл','s ply','однослойной','1-ой','1ply','однослойная','однослойный','однолойной']:
            equipment = 'Single-ply'
        elif word in ['экипировке','m ply','eq','многослой','экипировка']:
            equipment = 'Multi-ply'
        elif word in ['slinghot','sling-shot','soft','СПР','софт','облегченная','облегченной','слинг']:
            equipment = 'Multi-ply'
            event = 'B'
        elif 'бинт' in word or word == 'wraps':
            equipment = 'Wraps'
        elif word in ['безкипировки','raw','безэкип']:
            equipment = 'Raw'

        # Booleans.
        elif word == 'люб.' or word == 'любители':
            amateur = 'Amateur'
        elif word == 'pro' or word == 'pro-':
            assert amateur == 'Pro'


        # Grammatical ignorables.
        elif word == 'в':
            pass
        elif word == 'лежа':
            pass
        elif word == 'на':
            pass
        elif word == 'и':
            pass
        elif word == 'с':
            pass
        elif word == 'ст':
            pass

        # Other ignorables.
        elif word == 'сфо': # Not sure.
            pass
        elif word == 'становая' or word =='стан': # First word in 'deadlift'.
            pass
        elif 'экип' in word: #Equipment
            pass
        elif word == 'handicaped': #We don't seperately track Paralympic bench right now
            pass
        elif word in ['spr','ultra','standart','стандарт','ультра','шоте']: #Extra terms for slingshot bench
            pass
        elif word =='фжд': #Don't know what this means
            pass
        elif word == 'любители' or word =='любит' or word =='люб':#Amateur /Fan?
            pass
        elif word.strip() =='макс' or word =='максимум': #Maximum
            pass
        elif word == 'силовое': #Power. 
            pass
        elif word == 'двоеб': #Double
            pass
        elif word =='дивизион': #Division
            pass
        elif word =='мужчины': #Men
            pass
        elif word == 'воен': #Military
            pass
        elif word == 'лежа-народные': #Something to do with amateur bench, not sure
            pass
        elif word == 'забавы': #Fun? Maybe amateurs
            pass
        elif word =='поток': #Event?
            pass
        elif word =='абсолютка': #Results I think
            pass
        elif word =='лёжа': #Press
            pass
        elif word.isdigit():
            pass
        else:
            die('Fix parse_sheetname(): Unknown word "%s" in "%s"' % (word, s))
    assert event

    obj['event'] = event
    obj['amateur'] = amateur
    obj['equipment'] = equipment

    return obj


# Find the line that contains column information (the line below does also).
def get_header_linenum(sheet):
    for ii in range(len(sheet)):

        #Find name column
        for ii in range(len(sheet)):
            if is_header(''.join(sheet[ii])):
                return ii
    die("get_header_linenum() failed to find the header.")


def is_header(line):
    if 'ФИО' in line:
        return True
    return False	


# Header is two merged rows, recombine these back into one row here
def fix_headers(sheet):
    headernum=get_header_linenum(sheet)
    header = sheet[headernum]

    lineabove = sheet[headernum-1] #Need some error checking here
    linebelow = sheet[headernum+1]

    #Name has split below rest of data
    if header[0] == '' and lineabove[0] != '':
        header = [(lineabove[ii]+" "+header[ii]).strip() for ii in range(0,len(header))]
        sheet[headernum] =['' for x in header]
        headernum=headernum-1
    elif header[0] == '' and linebelow[0] != '':
        header = [(header[ii]+" "+linebelow[ii]).strip() for ii in range(0,len(header))]
        sheet[headernum-1] =['' for x in linebelow]
    elif header[0] != '' and linebelow[0] =='':
        header = [(header[ii]+" "+linebelow[ii]).strip() for ii in range(0,len(header))]
        sheet[headernum-1] =['' for x in linebelow]
    elif header[0] != '' and lineabove[0] =='' and not is_division(''.join(lineabove)):
        header = [(lineabove[ii] +" "+header[ii]).strip() for ii in range(0,len(header))]
        sheet[headernum-1] =['' for x in lineabove]

    sheet[headernum]=header

    return sheet


#Used for merging header lines correctly
def is_division(text):
    if 'категория' in text.lower():
        return True
    return False




def parse_fieldnames(sheet,obj):
    fieldnames = []

    headernum = get_header_linenum(sheet)
    header = sheet[headernum]
    # Name all the columns.
    iterable = iter(range(len(header)))
    for i in iterable:
        text = header[i].lower().replace('.','')

        if text == '№':
            fieldnames.append('IGNORE')
        elif text == 'фио' or text =='имя' or 'прізвище' in text:
            fieldnames.append('InternationalName')
        elif text == 'name':
            fieldnames.append('Name')
        elif text in['возраст']: 
            fieldnames.append('Age')
        elif 'дата' in text: #Catch all for birthyear 
            fieldnames.append('BirthYear')
        elif text in ['собств вес','собств','соб','вес','собственный вес','собственный','body weight','собcтвенный вес','собст вес','соб вес','собстввес','вага','св']:
            fieldnames.append('BodyweightKg')
        elif text in ['весовая категория','весовая кат','в/к']:
            fieldnames.append('WeightClassKg')
        elif text == 'team':
            fieldnames.append('Team')
        elif any(x in text  for x in['gloss','коэф','resh','залуцкий','рейшел','залутский']):
            fieldnames.append('IGNORE') # This is not the Wilks, but the WilksCoefficient.
        elif text == 'команда' or text =='coach': # Coach
            fieldnames.append('IGNORE')
        elif 'город' in text or 'регіон' in text:
            fieldnames.append('IGNORE') # We don't care about city-level information.
        elif text == 'сountry/city/state' or text =='страна/город/область' or text =='регион':
            fieldnames.append('Country/City/State')
        elif text =='итог' or text =='место' or text =='абсолютное первенство': #This is place, they only give top three so recalculate
            fieldnames.append('IGNORE')
        elif text =='пол': 
            fieldnames.append('Sex')
        elif text =='дивизион':
            fieldnames.append('Equipment')
        elif text == 'возрастная категория':
            fieldnames.append('Division')
        elif text =='дк':
            fieldnames.append('Tested')
        elif text == 'сумма subtotal':
            fieldnames.append('IGNORE')



        elif text in ['присед 1','squat 1','присяд 1','приседание 1','sq1','1 присед']:
            assert header[i+1].lower() in ['2','sq2','2 присед']
            assert header[i+2].lower() in ['3','sq3','3 присед']
            fieldnames.append('Squat1Kg')
            fieldnames.append('Squat2Kg')
            fieldnames.append('Squat3Kg')
            if  header[i+3].lower().replace('.','') in ['рек','rec','sq4','4 присед','4']:
                fieldnames.append('Squat4Kg')
                [next(iterable) for x in range(3)]
            else:
                [next(iterable) for x in range(2)]

        elif text in ['жим','жим 1','benchpress 1','жим макс кг 1','жим на максимум 1','жим вес','жим лежа 1','bp1','1 жим']:
            assert header[i+1].lower() in ['2','bp2','2 жим']
            assert header[i+2].lower() in ['3','bp3','3 жим']
            fieldnames.append('Bench1Kg')
            fieldnames.append('Bench2Kg')
            fieldnames.append('Bench3Kg')
            if  header[i+3].lower().replace('.','') in ['рек','rec','bp4','4 жим','4']:
                fieldnames.append('Bench4Kg')
                [next(iterable) for x in range(3)]
            else:
                [next(iterable) for x in range(2)]

        elif text in ['тяга','тяга 1','deadlift 1','становая тяга 1','dl1','1 тяга']:
            assert header[i+1].lower() in ['2','dl2','2 тяга']
            assert header[i+2].lower() in ['3','dl3','3 тяга']
            fieldnames.append('Deadlift1Kg')
            fieldnames.append('Deadlift2Kg')
            fieldnames.append('Deadlift3Kg')
            if  header[i+3].lower().replace('.','') in ['рек','rec','dl4','4 тяга','4']:
                fieldnames.append('Deadlift4Kg')
                [next(iterable) for x in range(3)]
            else:
                [next(iterable) for x in range(2)]


        elif text in ['1 подход']: #Attempts are just labelled "Attempt", use sheet title to find events
            assert header[i+1].lower() in ['2 подход']
            assert header[i+2].lower() in ['3 подход']

            if obj['event'] == 'S':
                fieldnames.append('Squat1Kg')
                fieldnames.append('Squat2Kg')
                fieldnames.append('Squat3Kg')
            elif obj['event'] == 'B':
                fieldnames.append('Bench1Kg')
                fieldnames.append('Bench2Kg')
                fieldnames.append('Bench3Kg') 
            elif obj['event'] == 'D':
                fieldnames.append('Deadlift1Kg')
                fieldnames.append('Deadlift2Kg')
                fieldnames.append('Deadlift3Kg')              

            if header[i+3].lower().replace('.','') in ['4 подход']:
                if obj['event'] == 'S':
                    fieldnames.append('Squat4Kg')
                elif obj['event'] =='B':
                    fieldnames.append('Bench4Kg')
                elif obj['event'] == 'D':
                    fieldnames.append('Deadlift4Kg')

                [next(iterable) for x in range(3)]
            else:
                [next(iterable) for x in range(2)]



        elif text in ['сумма','total','result','сумма баллов','резульат','результат bp','результат','рез-тат','итог сумма']:
            fieldnames.append('TotalKg')

        #Wilks/Schwartz/Gloss/Some other coefficient
        elif text.replace(' ','') in['wilks','wpoints','willks','очки','points','vilks','вилкс','абс','шварц/мелоун','шварц']:
            fieldnames.append('IGNORE')

        elif text == 'тренер':
            fieldnames.append('IGNORE')

        elif 'клуб' in text: #City/Club 
            fieldnames.append('IGNORE')
        elif text == 'страна':
            fieldnames.append('Country')
        elif text == 'норматив спр': #Not sure what this is
            fieldnames.append('IGNORE')
        elif text == '':
            fieldnames.append('IGNORE')

        else:
            die('Fix parse_fieldnames(): Unknown column header text: "%s"' % text)

    return fieldnames


# Given a list of lines all of which belong to the same sheet, parse that
# into an OpenPowerlifting-style CSV.
def parse_sheet(sheet):
    assert 'Sheet' in sheet[0][0]
    assert sheet[0][0].count(':') == 1

    csv = oplcsv.Csv()
    title =sheet[0][0].lower()
    # Ignore some sheets that don't contain any powerlifting.
    if 'судейская кол' in title:
        return csv
    elif 'нж' in title or 'народный' in title or 'русский' in title:
        return csv #Rep bench
    elif 'командный зачет' in title:
        return csv #Team results
    elif 'командное первенство' in title:
        return csv
    elif any(x in title for x in ['много','фжд','военный','1 вес','жд любители','армейский','тяговое','военный','двоеборье','1_2 веса']): #Bench reps
        return csv
    elif any(x in title for x in ['корпус','судейски','командный зачёт','абсолютный','судейство']): #Results
        return csv
    elif 'records' in title or 'рекорды' in title or 'командное' in title or 'тренерское' in title:
        return csv
    elif 'крж' in title: #??
        return csv
    elif 'чд' in title: #Not sure what theses pages are, some kind of reps contest
        return csv
    elif 'участников' in title: #Participants
        return csv
    elif 'абсолютка' in title: #Not sure what this is
        return csv
    elif 'армлифтинг' in title: #Armlifting
        return csv


    # Figure out everything we can from the sheet name
    obj = parse_sheetname(sheet[0][0].split(':')[1])


    #NAP often splits headers across multiple lines,fix this
    sheet = fix_headers(sheet)

    # Look through the sheet for column information and mark up the CSV.
    # All columns are given a name -- the extra ones are removed later.
    csv.fieldnames = parse_fieldnames(sheet,obj)

    append_equip = False
    append_div = False


    assert not 'Event' in csv.fieldnames
    csv.fieldnames.append('Event')

    csv.fieldnames.append('Amateur')



    #Equipment is sometimes given in columns, sometimes in sheet name
    if not 'Equipment' in csv.fieldnames:
        csv.fieldnames.append('Equipment')
        append_equip = True



    if not 'Division' in csv.fieldnames:
        csv.fieldnames.append('Division')
        append_div = True

    #Sex is sometimes given in columns, othertimes in headers
    if not 'Sex' in csv.fieldnames:
        csv.fieldnames.append('Sex')
        append_sex = True

    division = 'Open' #Sometimes division is just not given, default to Open
    sex = None


    #See if division is above the header
    one_before_header =''.join(sheet[get_header_linenum(sheet)-1])
    two_before_header = ''.join(sheet[get_header_linenum(sheet)-2])
    if 'категория' in one_before_header:
        division = one_before_header
    elif 'категория' in two_before_header:
        division = two_before_header


    # Iterate over each line, skipping the two header lines.
    for line in sheet[get_header_linenum(sheet)+1:]:
        text = ''.join(line)
        # Stop iteration once the 'Best Lifters' section is reached.
        if 'Абсолютный' in text or 'List absolute winners' in text or 'Возрастная группа' in text:
            break

        # Skip empty lines.
        if text == '':
            continue
        elif is_header(text): #Skip extra headers
            continue



        #Detect lines that set division
        if is_division(text):
            division = text
            continue

        #Detect lines that set sex
        if 'женщины' in text.lower():
        	sex = 'F'
        	continue
        elif 'мужчины' in text.lower():
        	sex = 'M'
        	continue

        # If we've made it this far, the line should be for a lifter!
        # Make sure they have a name!
        if 'InternationalName' in csv.fieldnames and not line[csv.index('InternationalName')]:
            continue
        if 'Name' in csv.fieldnames and not line[csv.index('Name')]:
            continue


        line.append(obj['event'])
        line.append(obj['amateur'])


        if append_equip or (line[csv.index('Equipment')] == '' and obj['equipment'] != None):
            if not append_equip:
                line[csv.index('Equipment')] = obj['equipment']
            else:
                line.append(obj['equipment'])



        if append_div:
        	line.append(division)
        else:
            line[csv.index('Division')] = division
                

        if append_sex:
        	line.append(sex)



        assert len(line) == len(csv.fieldnames)
        csv.rows.append(line)

    # Remove all the columns named 'IGNORE' before returning the CSV for integration.
    while 'IGNORE' in csv.fieldnames:
        csv.remove_column_by_name('IGNORE')

    unreverse_names(csv)

    return csv


# Handles the Division column
# Converts to English and separates into Division and Age columns.
def standardize_division(csv):
    assert 'Division' in csv.fieldnames
    assert 'Amateur' in csv.fieldnames

    dividx = csv.index('Division')
    amateuridx = csv.index('Amateur')
    for row in csv.rows:
        row[dividx]=row[dividx].replace(' - ','-')
        row[dividx]=row[dividx].replace('"','')
        row[dividx]= row[dividx].lower()

        row[dividx]=row[dividx].replace('абсолютка','')
        row[dividx]=row[dividx].replace('категория','')
        row[dividx]=row[dividx].replace('присед','')
        row[dividx]=row[dividx].replace('до','')
        row[dividx]=row[dividx].replace('пауэрлифтинг','')
        row[dividx]=row[dividx].replace('лет','')
        row[dividx]=row[dividx].replace('включительно','')
        row[dividx]=row[dividx].replace('жим','')
        row[dividx]=row[dividx].replace('лежа','')

        

        row[dividx]=row[dividx].strip()

        # Fill in the Division.
        # Handle the divisions with numbers first.
        if '18+' in row[dividx]:
            division = 'Open'
        elif '18' in row[dividx]:
            division = 'Teen under 18'
        elif '16-17' in row[dividx]:
            division = 'Teen 16-17'
        elif '15' in row[dividx]:
            division = 'Teen under 15'
        elif 'девушки' in row[dividx]:
            division = 'Women'

        elif 'юниоры' in row[dividx] or 'юноши' in row[dividx]or 'junior' in row[dividx]:
            division = 'Juniors'
        elif 'м1' in row[dividx]:
            division = 'Masters 1'
        elif 'masters 40-44' in row[dividx]:
            division = 'Masters 40-44'
        elif 'м2' in row[dividx]:
            division = 'Masters 2'
        elif 'masters 45-49' in row[dividx]:
            division = 'Masters 45-49'
        elif 'м3' in row[dividx]:
            division = 'Masters 3'
        elif 'masters 50-54' in row[dividx]:
            division = 'Masters 50-54'
        elif 'masters 55-59' in row[dividx]:
            division = 'Masters 55-59'
        elif 'м4' in row[dividx]:
            division = 'Masters 4'
        elif 'м5' in row[dividx]:
            division = 'Masters 5'
        elif 'masters 60-64' in row[dividx]:
            division = 'Masters 60-64'
        elif 'masters 65-69' in row[dividx]:
            division = 'Masters 65-69'
        elif 'masters 75-79' in row[dividx]:
            division = 'Masters 75-79'
        elif 'masters 80+' in row[dividx]:
            division = 'Masters 80+'            
        elif 'открытая' in row[dividx] or 'open' in row[dividx]:
            division = 'Open'
        elif row[dividx] =='':
            division = 'Open'
        else:
            die('Fix standardize_division(): Unknown division "%s"' % row[dividx])

        division = row[amateuridx] + ' ' + division
        row[dividx] = division.replace('  ',' ').strip()

    # Remove the now-extraneous columns.
    csv.remove_column_by_name('Amateur')



        
def unreverse_names(csv):

    if 'InternationalName' in csv.fieldnames:
        nameidx = csv.index('InternationalName')
    elif 'Name' in csv.fieldnames:
        nameidx= csv.index('Name')
    for row in csv.rows:
        parts = row[nameidx].split()
        parts = [name.title() for name in parts]

        # The last name is probably the given first name.
        fixed = [parts[-1]] + parts[:-1]
        name = ' '.join(fixed)

        row[nameidx] = name

#Names sometimes have something in brackets after them - extra divisions maybe?
def cleanup_names(csv):
    if 'InternationalName' in csv.fieldnames:
        nameidx = csv.index('InternationalName')
    elif 'Name' in csv.fieldnames:
        nameidx= csv.index('Name')

    for row in csv.rows:
        row[nameidx]= re.sub('\(.*\)','',row[nameidx])
        row[nameidx]=row[nameidx].strip()

def cleanup_lift(csv, fieldname):
    if fieldname in csv.fieldnames:
        idx = csv.index(fieldname)

        for row in csv.rows:
            amount = row[idx]

            amount = ''.join(c for c in amount if c.isdigit() or c in ['.','-'])
            amount = amount.replace('.00','').replace('.0','')


            if amount == 'X' or amount.replace('-','') == '0' or not any(c.isdigit() for c in amount):
                amount = ''

            #Sometimes numbers have more than 2 commas, if so remove the second one
            if len([ii for ii, a in enumerate(amount) if a == '.']) >1:
                amount = amount[:amount.rfind('.')]+amount[amount.rfind('.')+1:]

            row[idx] = amount


#Remove '.0' from weightclasses
def cleanup_weightclass(csv):
    idx = csv.index('WeightClassKg')
    for row in csv.rows:
        if '.0' in row[idx]:
            row[idx] = row[idx].replace('.0','')

#Sometimes weight class is also given after bodyweight
def cleanup_bodyweight(csv):
    idx = csv.index('BodyweightKg')
    for row in csv.rows:
        if row[idx] != '':
            row[idx]=row[idx].split()[0]

#If an equipment column was given initially standardise it
def cleanup_equipment(csv):
    eqpidx = csv.index('Equipment')
    for row in csv.rows:
        if row[eqpidx].lower()=='raw':
            row[eqpidx]='Raw'
        elif row[eqpidx].lower() =='soft':
            row[eqpidx]='Single-ply'

#If sex was given standardise it
def cleanup_sex(csv):
    if 'Sex' in csv.fieldnames:
        sexidx = csv.index('Sex')
        for row in csv.rows:
            if row[sexidx].lower()=='ж':
                row[sexidx]='F'
            elif row[sexidx].lower() =='м':
                row[sexidx]='M'

#If birthdate was given, keep only the year
def cleanup_birthyear(csv):
    if 'BirthYear' in csv.fieldnames:
        byidx = csv.index('BirthYear')
        for row in csv.rows:
            row[byidx] = max(re.split('[. - /]',row[byidx]),key=len)

def cleanup_tested(csv):
    if 'Tested' in csv.fieldnames:
        tstidx = csv.index('Tested')
        for row in csv.rows:
            if row[tstidx].lower()=='да':
                row[tstidx]='Yes'
            elif row[tstidx].lower() =='нет':
                row[tstidx]='No'

def assign_best(csv, liftname):
    idx1 = csv.index('%s1Kg' % liftname)
    idx2 = csv.index('%s2Kg' % liftname)
    idx3 = csv.index('%s3Kg' % liftname)
    bestidx = csv.index('Best%sKg' % liftname)

    def weight(str):
        try:
            return float(str)
        except ValueError:
            return 0.0

    for row in csv.rows:
        best = max(weight(row[idx1]), weight(row[idx2]), weight(row[idx3]))

        if float(best) > 0:
            row[bestidx] = str(best)


def assign_total(csv):

    if 'TotalKg' not in csv.fieldnames:
        csv.append_column('TotalKg')
    idx = csv.index('TotalKg')

    def weight(str):
        try:
            return float(str)
        except ValueError:
            return 0.0

    for row in csv.rows:
        if row[idx] == '':
            total = 0.0
            if 'BestSquatKg' in csv.fieldnames:
                total += weight(row[csv.index('BestSquatKg')])
            if 'BestBenchKg' in csv.fieldnames:
                total += weight(row[csv.index('BestBenchKg')])
            if 'BestDeadliftKg' in csv.fieldnames:
                total += weight(row[csv.index('BestDeadliftKg')])

            if total != 0.0:
                row[idx] = str(total) 


def main(filename):
    # Since the input is comma-separated, store the file as a list of lists.
    with open(filename) as fd:
        lines = [x.strip().split(',') for x in fd.readlines()]
    
    # Split the input filename into sheets, each of which is an independent CSV.
    sheetlist = split_by_sheet(lines)

    # Parse each sheet independently, then join them all together into a single CSV.
    csv = oplcsv.Csv()
    for sheet in sheetlist:
        sheetcsv = parse_sheet(sheet)
        csv.cat(sheetcsv)


    for x in ['Squat1Kg', 'Squat2Kg', 'Squat3Kg','Squat4Kg', 'Bench1Kg', 'Bench2Kg', 'Bench3Kg','Bench4Kg',
            'Deadlift1Kg', 'Deadlift2Kg', 'Deadlift3Kg','Deadlift4Kg', 'TotalKg']:
        cleanup_lift(csv, x)

    if 'BestSquatKg' in csv.fieldnames:
        cleanup_lift(csv,'BestSquatKg')
    if 'BestBenchKg' in csv.fieldnames:
        cleanup_lift(csv,'BestBenchKg')
    if 'BestDeadliftKg' in csv.fieldnames:
        cleanup_lift(csv,'BestDeadliftKg')

    if 'BestSquatKg' not in csv.fieldnames and 'Squat1Kg' in csv.fieldnames:
        csv.append_column('BestSquatKg')
        assign_best(csv, 'Squat')
    if 'BestBenchKg' not in csv.fieldnames and 'Bench1Kg' in csv.fieldnames:
        csv.append_column('BestBenchKg')
        assign_best(csv, 'Bench')
    if 'BestDeadliftKg' not in csv.fieldnames and 'Deadlift1Kg' in csv.fieldnames:
        csv.append_column('BestDeadliftKg')
        assign_best(csv, 'Deadlift')


    # Now it's time to standardize the CSV a little bit!
    # We have some temporary columns hanging out.
    standardize_division(csv)
    cleanup_names(csv)
    cleanup_weightclass(csv)
    cleanup_bodyweight(csv)
    cleanup_equipment(csv)
    cleanup_sex(csv)
    cleanup_birthyear(csv)
    cleanup_tested(csv)

    assign_total(csv)


    csv.write(sys.stdout)
    return 0


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(" Usage: %s results.csv > entries.csv" % sys.argv[0])
        sys.exit(1)
    sys.exit(main(sys.argv[1]))
